import { faker } from "@faker-js/faker";

export const availableFields = {
    id: () => Math.floor(Math.random() * 10000).toString(),
    first_name: () => faker.person.firstName(),
    firstName: () => faker.person.firstName(),
    name: () => faker.person.firstName(),
    last_name: () => faker.person.lastName(),
    lastName: () => faker.person.lastName(),
    surname: () => faker.person.lastName(),
    middle_name: () => faker.person.middleName(),
    middleName: () => faker.person.middleName(),
    gender: () => faker.person.gender(),
    sex: () => faker.person.sexType(),
    email: () => faker.internet.email(),
    passwordHash: () => faker.string.uuid(),
    password_hash: () => faker.string.uuid(),
    birthdate: () => faker.date.birthdate(),
    dateOfBirth: () => faker.date.birthdate(),
    registeredAt: () => faker.date.past(),
    registered_at: () => faker.date.past(),
    createdAt: () => faker.date.past(),
    created_at: () => faker.date.past(),
    updatedAt: () => faker.date.past(),
    updated_at: () => faker.date.past(),
    isOnboarded: () => faker.datatype.boolean(),
    is_onboarded: () => faker.datatype.boolean(),
    theme: () => faker.color.human(),
    country: () => faker.location.county(),
    phoneNumber: () => faker.phone.number(),
    phone_number: () => faker.phone.number(),
    avatarLink: () => faker.string.uuid(),
    emailVerified: () => faker.datatype.boolean(),
    email_verified: () => faker.datatype.boolean(),
    verified: () => faker.datatype.boolean(),
    isBlocked: () => faker.datatype.boolean(),
    is_blocked: () => faker.datatype.boolean(),
};
